name: Build and Zip Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mode: [fontawesome, nofontawesome]

    steps:      
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install
      
      - name: Build project for ${{ matrix.mode }} mode
        run: npm run build:${{ matrix.mode }}
      
      - name: Create Zip Archive
        run: zip -r build-${{ matrix.mode }}.zip build/dist-${{ matrix.mode }}
      
      - name: Upload Zip Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.mode }}
          path: build-${{ matrix.mode }}.zip
